import { createSlice } from '@reduxjs/toolkit';

import { searchPropertyAsync } from './thunks';
import { SearchPropertyState } from './types';

const initialState: SearchPropertyState = {
  data: [],
  status: 'idle',
};

export const searchPropertiesSlice = createSlice({
  name: 'searchProperties',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    clearState: (state) => {
        state.data = []
        state.status = 'idle'
      }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(searchPropertyAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(searchPropertyAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload.data;
      });
  },
});

export default searchPropertiesSlice;
